[carton_animals]
title="Cartoon Animals"
items=["Garfield", "Scooby-Doo", "Yogi Bear", "Bugs Bunny", "Mickey Mouse", "Goofy", "Jiminy Cricket", "Danger Mouse", "Nemo", "Tony the Tiger", "Snoopy", "Bambi", "Dumbo", "Paddington Bear", "Simba", "Sonic the Hedgehog"]

[countries]
title="Countries"
items=["UK", "Spain", "Japan", "Brazil", "France", "USA", "Italy", "Australia", "Germany", "Mexico", "India", "Israel", "Canada", "China", "Russia", "Egypt"] 
title_pl="Państwa"
items_pl=["Wielka Brytania", "Hiszpania", "Japonia", "Brazylia", "Francja", "Stany Zjednoczone", "Włochy", "Australia", "Niemcy", "Meksyk", "Indie", "Izrael", "Kanada", "Chiny", "Rosja", "Egipt"]


[phobias]
title="Phobias"
items=["Ghosts", "Spiders", "Monsters", "Rats", "Toilets", "Snakes", "Germs", "Clowns", "Needles", "Dogs", "Birds", "Insects", "Children", "Shadows", "Roller Coasters", "Planes"]
title_pl="Fobie"
items_pl=["Duchy", "Pająki", "Potwory", "Szczury", "Toalety", "Węże", "Bakterie", "Klauni", "Igły", "Psy", "Ptaki", "Owady", "Dzieci", "Cienie", "Kolejki górskie", "Samoloty"]
title_pl="Fobie"


[hobbies]
title="Hobbies"
items=["Stamps", "Trains", "Model making", "Knitting", "Fishing", "Reading", "Painting", "Gardening", "Sailing", "Travel", "Walking", "Pottery", "Cooking", "Yoga", "Photography", "Hiking"]


[games]
title="Games"
items=["Monopoly", "Scrabble", "Mouse Trap", "Gues Who", "Risk", "Operation", "Twister", "Pictionary", "Battleship", "Backgammon", "Cluedo", "Chess", "Draughts", "Trivial Pursuit", "Jenga", "Hungry Hungry Hippos"]



[fictional_charactes]
title="Fictional Characters"
items=["Indiana Jones", "Marry Poppins", "Spiderman", "Catwoman", "James Bond", "Wonder Woman", "Princess Leia", "The Little Mermaid", "Dracula", "Lara Croft", "Robin Hood", "Hermiona Grenger", "Super Mario", "Homer Simpson", "Hercules", "Katniss Everdeen"]


[sport_stars]
title="Sport Stars"
items=["Tiger Wood", "Pelé", "Michael Jordan", "David Beckham", "Michael Phelps", "Serena Williams", "Muhammad Ali", "Kelly Holmes", "Bradley Wiggins", "Johny Wilkinson", "Ronnie O'Sullivan", "Jess Ennis-Hill", "Lewis Hamilton", "Andy Murray", "Usain Bolt", "Laura Trott"]


[musical_instruments]
title="Musical Instruments"
items=["Electric Guitar", "Piano", "Violin", "Drums", "Bass Guitar", "Saxophone", "Cello", "Flute", "Clarinet", "Trumpet", "Voice", "Ukulele", "Harp", "Bagpipes", "Harmonica", "Banjo"]


[food]
title="Food"
items=["Pizza", "Potatoes", "Fish", "Cake", "Pasta", "Salad", "Soup", "Bread", "Eggs", "Cheese", "Fruit", "Chicken", "Sausage", "Ice Cream", "Chocolate", "Beef"]


[inventions]
title="Inventions"
items=["Matches", "Gunpowder", "Wheel", "Printing", "Computer", "Internet", "Compass", "Plane", "TV", "Electricity", "Writing", "Steam Engine", "Car", "Telephone", "Camera", "Radio"]


[tv_shows]
title="TV Shows"
items=["Friends", "Sex and the City", "Star Trek", "Only Fools and Horses", "Breaking Bad", "Coronation Street", "Little Britain", "Blackadder", "Happy Days", "The X-Files", "Fawlty Towers", "The Office", "Mad Man", "The Simpsons", "Game of Thrones", "Eastenders"]


[toys]
title="Toys"
items=["Lego", "Rocking Horse", "Super Soaker", "Beanie Babies", "Rubik's Cube", "Etch a Sketch", "Teddy Bear", "Play Doh", "Yo-yo", "Fresbee", "Hot Wheels", "Barbie", "Slinky", "G.I. Joe", "Hula Hoop", "Swingball"]


[film_genres]
title="Film Genres"
items=["Horror", "Action", "Thriller", "Sci-Fi", "Rom-Com", "Western", "Comedy", "Christmas", "Gangster", "Foreign Language", "War", "Documentary", "Musical", "Animation", "Zombie", "Sport"]



[civilizations]
title="Civilizations"
items=["Romans", "Egyptians", "Mayans", "Mongols", "Aztecs", "Japanese", "Persians", "Greeks", "Turks", "Vikings", "Incas", "Spanish", "Zulu", "Chinese", "Spartans", "Aliens"]


[music]
title="Music"
items=["Rock", "Heavy Metal", "Classical", "Funk", "Hip Hop", "Pop", "Techno", "Blues", "Rap", "Punk", "Indie", "Christmas", "Country", "House", "Disco", "Reggae"]


[celebrations]
title="Celebrations"
items=["Christmas", "Father's Day", "St Patrick Day", "Easter", "St George's Day", "April Fool's Day", "Boxing Day", "Valentine's Day", "Pancake Day", "Bonfire Night", "Queen's Jubilee", "Mother's Day", "New Year's Eve", "Burns Night", "May Day", "Halloween"]



[school]
title="School"
items=["Mathd", "Chemistry", "Physics", "Biology", "History", "Philosophy", "Geography", "English", "Economics", "French", "Art", "Music", "P.E.", "Latin", "Religion", "Technology"]


[movies]
title="Movies"
items=["Jurassic Park", "Jaws", "Raiders of the Lost Ark", "The Avenger's", "Transformers", "Toy Story", "Home Alone", "Titanic", "E.T.", "The Wizard of Oz", "King Kong", "The Matrix", "Shrek", "The Godfather", "Finding Nemo", "Avatar"]


[geography]
title="Geography"
items=["Lake", "Sea", "Valley", "Mountain", "River", "Desert", "Ocean", "Forest", "Jungle", "Island", "Glacier", "Waterfall", "Volcano", "Cave", "Arctic", "Swamp"]


[bands]
title="Bands"
items=["The Beatles", "The Rolling Stones", "AC/DC", "Nirvana", "Take That", "One Direction", "Guns N' Roses", "Queen", "The Breach Boys", "Red Hot Chili Peppers", "KISS", "Jackson 5", "ABBA", "The Eagles", "The Who", "U2"]


[children_books]
title="Children's Books"
items=["The Hobbit", "Peter Pan", "The Vey Hungry Caterpillar", "101 Dalmatians", "Matilda", "Harry Potter", "Alice in Wonderland", "The Lion, the Witch and the Wardrobe", "Wind in the Willows", "The Cat in the Hat", "Charlie and the Chocolate Factory", "Where the Wild Things Are", "Winnie-the-Pooh", "Stig of the Dump", "The Jungle Book", "Charlotte's Web"]


[under_the_sea]
title="Under the Sea"
items=["Octopus", "Starfish", "Shark", "Jellyfish", "Lobster", "Seal", "Dolphin", "Killer Whale", "Crab", "Giant Squid", "Seahorse", "Stingray", "Sea Turtle", "Clownfish", "Swordfish", "Mermaid"]



[historical_figures]
title="Historical Figures"
items=["Jesus", "Napoleon", "Staling", "Hitler", "Darwin", "Martin Luther King", "Aung San Suu Kyi", "Einstein", "Christopher Columbus", "Mother Teresa", "Florence Nightingale", "Joan of Arc", "Mozart", "Clepatra", "Buddha", "Winston Churchill"]


[mythical_creatures]
title="Mythical Creatures"
items=["Cyclops", "Pegasus", "Medusa", "Sphinx", "Werewolf", "Unicorn", "Dragon", "Troll", "Loch Ness Monster", "Mermaid", "Phoenix", "Vampire", "Minotaur", "Hydra", "Yeti", "Centaur"]


[drinks]
title="Drinks"
items=["Coffee", "Tea", "Lemonade", "Coca-Cola", "Wine", "Beer", "Punch", "Tequila", "Hot Chocolate", "Milkshake", "Ginger Beer", "Water", "Smoothie", "Orange Juice", "Milk", "Champagne"]


[sports]
title="Sports"
items=["Football", "Cricket", "Golf", "Snooker", "Basketball", "Rugby", "Sailing", "Squash", "Tennis", "Badminton", "Motor Racing", "Wrestling", "Lacrosse", "Volleyball", "Triathlon", "Cycling"]


[sci_fi_fantasy]
title="Sci-Fi & Fantasy"
items=["Star Wars", "Lord of the Rings", "Star Trek", "Blade Runner", "The Adams Family", "2001L A Space Odyssey", "Terminator", "His Dark Materials", "Dune", "The Princess Bride", "Alice's adventures in Wonderland", "Gulliver's Travels", "The War of the Worlds", "The Martian", "WALL-E", "Edward Scissorhands"]


[transport]
title="Transport"
items=["Plane", "Car", "Tank", "Helicopter", "Cruise Ship", "Hovercraft", "Motorbike", "Bus", "Segway", "Cable Car", "Jet Ski", "Hot Air Balloon", "Train", "Spaceship", "Magic Carpet", "Broomstick"]


[jobs]
title="Jobs"
items=["Fisherman", "Lumberjack", "Nurse", "Waiter", "Lighthouse Keeper", "Secretary", "Accountant", "Teacher", "Lorry Driver", "Security Guard", "Chef", "Architect", "Police Officer", "Lawyer", "Carpenter", "Butcher"]


[rooms]
title="Rooms"
items=["Kitchen", "Hallway", "Greenhouse", "Bedroom", "Bathroom", "Dinig Room", "Office", "Living Room", "Attic", "Basement", "Dungeon", "Nursery", "Pantry", "Bunker", "Shed", "Garage"]


[zoo]
title="Zoo"
items=["Elephant", "Giraffe", "Koala", "Tiger", "Lion", "Leopard", "Meerkat", "Buffalo", "Ostrich", "Owl", "Eagle", "Parrot", "Scorpion", "Alligator", "Zebra", "Gorilla"]


[fairy_tales]
title="Fairy Tales"
items=["Cinderella", "Goldilocks", "Jack and the Beanstalk", "Hare and the Tortoise", "Snow White", "Rapunzel", "Aladdub", "Princess and the Pea", "Peter Pan", "Little Red Riding Hood", "Pinocchio", "Beauty and the Beast", "Sleeping Beauty", "Hansel and Greatel", "Gingerbread Man", "Three Little Pigs"]

[authors]
title="Authors"
items=["Shakespeare", "Tolkien", "C.S. Lewis", "J.K. Rowling", "Stephen King", "Earnest Hemingway", "Roald Dalhi", "Charles Dickens", "Rudyard Kipling", "Tolstoy", "Jane Austin", "Mark Twain", "Danielle Steel", "John Grisham", "Dan Brown", "Agatha Christie"]

[cities]
title="Cities"
items=["New York City", "Moscow", "Delhi", "London", "Paris", "Rome", "Rio de Janeiro", "Sydney", "Tokyo", "Athens", "Cairo", "Hong Kong", "Chicago", "Los Angeles", "San Francisco", "Jerusalem"]

[artists]
title="Artists"
items=["Damien Hirst", "Salvador Dali", "Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Andy Warhol", "Leonardo da Vinci", "Micheloangelo", "Banksy", "David Hockney", "Greyson Perry", "J. M. W. Turner", "Rembrandt", "Jackson Pollock", "L. S. Lowery", "William Blake"]

[the_arts]
title="The Arts"
items=["Painting", "Sculpture", "Architecture", "Dance", "Literature", "Opera", "Stand-up", "Comic Books", "Illustration", "Music", "Thetre", "Cinema", "Video Games", "Graffiti", "Fashion", "Photography"]

[world_wonders]
title="World Wonders"
items=["Pyramids", "Eiffel Tower", "Statue of Liberty", "Big Ben", "Stonehenge", "Angkor Wat", "Collosseum", "Sydney Opera House", "Christ the Redeemer", "Machu Pichu", "Taj Mahal", "Petra", "Great Wall of China", "Acropolis", "Empire State Building", "Keaning Tower of Piza"]

[tattoos]
title="Tattoos"
items=["Stars", "Angel", "Wings", "Dragon", "Eagle", "Fairy", "Heart", "Skull", "Sword", "Tiger", "Swallows", "Flower", "Butterfly", "Cross", "Owl", "Anchor"]


[wedding_anniversaries]
title="Wedding Anniversaries"
items=["Wood", "China", "Paper", "Cotton", "Bronze", "Gold", "Ruby", "Diamond", "Crystal", "Flowers", "Silk", "Leather", "Pearl", "Coral", "Tin", "Wool"]

[musicals]
title="Musicals"
items=["West Side Story", "Cats", "Jersey Boys", "School of Rock", "Phantom of the Opera", "Les Miserables", "Oliver", "Hamilton", "Chicago", "42nd Street", "Annie", "Book of Mormon", "Lion King", "Wicked", "Hairspray", "Mamma Mia"]

